### ISSUE TITLE
[Bug] Uploading images on the feature detail comments page fails

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#1408]
Uploading an image to a feature detail page fails, e.g. https://app.growthbook.io/features/donut_price

The user experience around that is pretty poor too—when it fails, it uses a window.alert which blocks the page and makes it a bit annoying to debug.

Further details:

- SaaS app (also happens with self-hosted, see comments below)
- Failed 3 out of 4 attempts, succeeded 1

Updates:

- 21 Aug 2023: Also happens when requesting the image, not just uploading (see comments below)

![CleanShot 2023-06-27 at 11 16 16@2x](https://github.com/growthbook/growthbook/assets/113377031/453d8726-5e68-47eb-9d7f-60a74832b463)

<img width="810" alt="image" src="https://github.com/growthbook/growthbook/assets/113377031/f24eec51-ae51-4ab4-ba54-255438e39499">

<img width="481" alt="image" src="https://github.com/growthbook/growthbook/assets/113377031/86841732-ba2a-48d5-9b9c-a5b67a716c18">

**Comment by marcelinho09** [comment]
I think what you actually have to do here first is configure CORS on your S3 bucket, something like that:

[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "https://yourdomain.com"
        ],
        "ExposeHeaders": []
    }
]

This atleast solves the CORS issue for me, but anyhow I'm still having 400 Bad Requests after CORS is working.

**Comment by marcelinho09** [comment]
Oh well, after a second thought I have to add that we're trying to use self-hosted. Not sure if this applies to the SaaS-version.

**Comment by tinahollygb** [comment]
Thanks for confirming @fabianmarinog ... It looks like this issue happens on both self-hosted and the cloud version. And it appears to impact reading too, not just uploading. I'll update the issue to include that.

**Comment by jdorn** [comment]
This should be resolved now. Let us know if you continue to experience issues.

**Comment by abozaid0ibrahim** [comment]
I still face this issue, I upload the image to the variations  and after reload I dont find it, i tried couple of times, never mangaed to get GB saves my images.
